PROJECT = server
PROJECT_DESCRIPTION = gaeraned gateway server
PROJECT_VERSION = 0.1.0

DEPS = cowboy eredis json
dep_cowboy_commit = 2.9.0
dep_jsx = git https://github.com/talentdeficit/jsx main

DEP_PLUGINS = cowboy

include erlang.mk
